# Generated by Django 2.2 on 2019-04-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_of_recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='ingridients',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='SubTest',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
